entelib/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls.defaults import *
import settings

urlpatterns = patterns('',
    (r'^entelib/', include('entelib.baseapp.urls')),
    (r'^' + settings.MEDIA_URL[1:] + '(?P<path>.*)$',  'django.views.static.serve',  { 'document_root': settings.MEDIA_ROOT, }),
    (r'^$', 'django.views.generic.simple.redirect_to', {'url': '/entelib/'}),
)


if settings.IS_DEV:
    from django.contrib.auth import authenticate, login
    from django.contrib.auth.models import User
    from django.http import HttpResponseRedirect

    def _login_user(request):
        user = authenticate(username='user', password='user')
        login(request, user)
        return HttpResponseRedirect('/')
    def _login_lib(request):
        user = authenticate(username='lib', password='lib')
        login(request, user)
        return HttpResponseRedirect('/')
    def _login_admin(request):
        user = authenticate(username='admin', password='admin')
        login(request, user)
        return HttpResponseRedirect('/')

    urlpatterns += patterns('',
        (r'_login_user', 'entelib.urls._login_user'),
        (r'_login_lib', 'entelib.urls._login_lib'),
        (r'_login_admin', 'entelib.urls._login_admin'),
    )

entelib/baseapp/forms.py
# -*- coding: utf-8 -*-
from django import forms
from django.contrib.auth.models import Group, User
from baseapp.models import Book, BookRequest, Building, PhoneType, Phone,\
    Location, BookCopy, Category, Author, Publisher, CostCenter, State
# from baseapp.models import CustomUser
from config import Config
from baseapp.utils import pprint
import baseapp.utils as utils
from copy import copy
from baseapp.views_aux import get_phones_for_user
from django.core.exceptions import ObjectDoesNotExist
from django.forms.models import ModelForm
from django.db.models.query_utils import Q
import models_config as CFG
from baseapp.config import ConfigValueTypeHelper

attrs_dict = { 'class': 'required' }



class ConfigOptionEditForm(forms.Form):
    """
    Form for editing config's option.
    """
    value        = forms.CharField(required=True, widget=forms.Textarea)
    can_override = forms.BooleanField(required=False)
    description  = forms.CharField(required=False, widget=forms.Textarea, max_length=CFG.configuration_descirption_len)

    def __init__(self, user, option_key, config, is_global, *args, **kwargs):
        super(ConfigOptionEditForm, self).__init__(*args, **kwargs)
        self.user = user
        self.option_key = option_key
        self.is_global = is_global
        self.config = config
        type = self.config.get_type(self.option_key)
        self.fields['value'] = ConfigValueTypeHelper().get_form_widget_for_type(type.name)

    def clean_description(self):
        if self.is_global:
            if len(self.cleaned_data['description']) < 2:
                raise forms.ValidationError('Description cannot be empty')
            return self.cleaned_data['description']
        else:
            return ''

    def clean_value(self):
        if not 'value' in self.cleaned_data:
            raise forms.ValidationError(u'Value must have any value')
        config = self.config
        value = self.cleaned_data['value']
        type = config.get_type(self.option_key)

        parsers = ConfigValueTypeHelper().get_parsers()

        for typename, v in parsers.items():
            if type.name == typename:
                try:
                    cast_value = v['parse_fun'](value)
                except ValueError, e:
                    if 'error_msg' in v:
                        msg = v['error_msg']
                    else:
                        msg = unicode(e)
                    raise forms.ValidationError(msg)
                else:
                    return cast_value
        else:
            raise forms.ValidationError('Unable to verify type. Please contact admin or developer.')
        return value

    def clean(self):
        config = self.config
        key = self.option_key
        is_global = self.is_global
        if not is_global:
            if not config.can_override(key):
                raise forms.ValidationError(u"Key %s cannot be overriden" % (key,))
        else:
            pass
        return self.cleaned_data

    def save(self):
        key = self.option_key
        config = self.config
        if self.is_global:
            config.set_global_value(key, self.cleaned_data['value'])
            config.set_can_override(key, self.cleaned_data['can_override'])
            config.set_description(key, self.cleaned_data['description'])
        else:
            config[key] = self.cleaned_data['value']


class ProfileEditChoiceList:
    @staticmethod
    def buildings():
        """ Builds list od 2-tuples containing Buildings. """
        choice_list =  [ (0, u'--- not specified ---')]
        choice_list += [(b.id, b.name)  for b in Building.objects.order_by('name').all()]
        return choice_list

    @staticmethod
    def phone_types():
        """ Builds list of 2-tuples containing PhoneTypes. """
        return [(pt.id, pt.name) for pt in PhoneType.objects.order_by('name').all()]

class ProfileEditForm(forms.Form):
    """
    Form for editing user profile.
    User can edit their both email and password.
    The new password must be entered twice in order to catch typos.

    Empty field = no edition.
    """

    phone_prefix = 'phone'
    phone_type_prefix = phone_prefix + 'Type'
    phone_value_prefix = phone_prefix + 'Value'

    username = forms.CharField(help_text=u'Required. 30 characters or fewer. Letters, numbers and @/./+/-/_ characters', max_length=30, label=u'Username')
    first_name = forms.CharField(max_length=30, required=False, label=u'First name')
    last_name = forms.CharField(max_length=30, required=False, label=u'Last name')
    email = forms.EmailField(label=(u'E-mail'), required=False)
    work_building = forms.ChoiceField(choices=ProfileEditChoiceList.buildings(), label="Building I work in")
    location_remarks = forms.CharField(max_length=CFG.location_remarks_len, label=u'My location details')
    groups = forms.CharField(label='helo')

    phoneType0 = forms.ChoiceField(choices=ProfileEditChoiceList.phone_types(), label='Phone 0', required=False)
    phoneValue0 = forms.CharField(label='', required=False)

    phoneType1 = forms.ChoiceField(choices=ProfileEditChoiceList.phone_types(), label='Phone 1', required=False)
    phoneValue1 = forms.CharField(label='', required=False)

    phoneType2 = forms.ChoiceField(choices=ProfileEditChoiceList.phone_types(), label='Phone 2', required=False)
    phoneValue2 = forms.CharField(label='', required=False)

    phoneType3 = forms.ChoiceField(choices=ProfileEditChoiceList.phone_types(), label='Phone 3', required=False)
    phoneValue3 = forms.CharField(label='', required=False)

    phoneType4 = forms.ChoiceField(choices=ProfileEditChoiceList.phone_types(), label='Phone 4', required=False)
    phoneValue4 = forms.CharField(label='', required=False)

    current_password = forms.CharField(widget=forms.PasswordInput(render_value=False),
        label=(u'Your password'), required=True)
    password1 = forms.CharField(widget=forms.PasswordInput(render_value=False),
        label=(u'New password'), required=False)
    password2 = forms.CharField(widget=forms.PasswordInput(render_value=False),
        label=(u'New password (again)'), required=False)



    def __init__(self, profile_owner, editor=None, *args, **kwargs):
        """
        profile_owner is instance of User, whose profile will be changed.
        editor is instance of User, who will change the profile.

        If editor is None, then it is set to profile_owner
        """
        if editor:
            self.editor = editor
        else:
            self.editor = profile_owner
        self.profile_owner = profile_owner
        super(ProfileEditForm, self).__init__(*args, **kwargs)
        # editing username, first name and last name requires perm
        if not self.editor.has_perm('baseapp.edit_xname'):
            self.fields['username'].widget.attrs['readonly'] = True
            self.fields['first_name'].widget.attrs['readonly'] = True
            self.fields['last_name'].widget.attrs['readonly'] = True

        # groups form
        if self.editor.has_perm('baseapp.assign_user_to_groups'):
            self.fields['groups'] = forms.ModelMultipleChoiceField(Group.objects.all().order_by('name'), required=False)
        else:
            self.fields['groups'] = forms.CharField(label='Groups')
            self.fields['groups'].widget.attrs['readonly'] = True


    def clean(self):
        """
        Check if passwords matches (these are 'new password' and 'again new password')
        """
        if not ('password1' in self.cleaned_data and 'password2' in self.cleaned_data):
            return self.cleaned_data
        if self.cleaned_data['password1'] != self.cleaned_data['password2']:
            raise forms.ValidationError(u'You must type the same new password each time.')
        return self.cleaned_data


    def clean_current_password(self):
        """
        Verify that the password user typed as their current one is correct.
        """
        if not 'current_password' in self.cleaned_data:
            return self.cleaned_data
        if not self.editor.check_password(self.cleaned_data['current_password']):
            raise forms.ValidationError(u'The password is incorrect.')
        return self.cleaned_data


    def clean_first_name(self):
        # exit if unchanged
        if self.profile_owner.first_name == self.cleaned_data['first_name']:
            return self.profile_owner.first_name
        # check perms
        if not self.editor.has_perm('baseapp.edit_xname'):
            raise forms.ValidationError("You don't have permissions to edit first name")

        value = self.cleaned_data['first_name']
        if len(value) > 30:
            raise forms.ValidationError('Too long')
        return value

    def clean_last_name(self):
        # exit if unchanged
        if self.profile_owner.last_name == self.cleaned_data['last_name']:
            return self.profile_owner.last_name
        # check perms
        if not self.editor.has_perm('baseapp.edit_xname'):
            raise forms.ValidationError("You don't have permissions to edit last name")

        value = self.cleaned_data['last_name']
        if len(value) > 30:
            raise forms.ValidationError('Too long')
        return value

    def clean_email(self):
        given_email = self.cleaned_data['email']
        cleaned_email = given_email

        # is not taken (excluding me)
        is_taken = 0 < User.objects.filter(email__iexact=given_email) \
                                   .exclude(id=self.profile_owner.id) \
                                   .count()
        if is_taken:
            raise forms.ValidationError('E-mail already taken')
        return cleaned_email

    def clean_username(self):
        # exit if unchanged
        if self.profile_owner.username == self.cleaned_data['username']:
            return self.profile_owner.username
        # check perms
        if not self.editor.has_perm('baseapp.edit_xname'):

entelib/templates/config/edit_option.html
{% extends 'base_with_top_menu.html' %}

{% block title %}Edit config option{% endblock %}

{% block header %}Edit {%if is_global%}global {%endif%}config option{% endblock %}

{% block content %}

{% if form %}
<div class="formWrapper">
  <form class="edit_option_form" action="." method="POST">
    <table class="basic_fields">
      <tbody>
        {% if form.non_field_errors %}
        <tr><td>{{form.non_field_errors}}</td></tr>
        {% endif %}
        <tr><td class="key"><span class="label">Key:</span> {{form.option_key}} </td> </tr>
        {% if is_global %}
        <tr><td class="description"><span class="label">Description:</span> <br/>{{form.description}} {{form.description.errors}}</td> </tr>
        <tr><td class="can_override"><label for="id_can_override"><span class="label">Can override:</span></label> {{form.can_override}}</td> </tr>
        <tr><td class="global_value"><span class="label">Global value:</span> <br/>{{ form.value.errors }} {{ form.value }} </td></tr>
        {% else %}
        <tr><td class="description"><span class="label">Description:</span> {{option.description|linebreaksbr}} </td> </tr>
        <tr><td class="can_override"><span class="label">Can override:</span> {{option.can_override}} </td> </tr>
        <tr><td class="value"><span class="label">Value:</span> <br/>{{ form.value.errors }} {{ form.value }} </td></tr>
        {% endif %}
        <tr> <th></th> <td><input type="submit" value="Save changes"/></td> </tr>
      </tbody>
    </table>
  </form>
</div>

{% endif %}

{% endblock %}

entelib/templates/config/list.html
{% extends 'base_with_top_menu.html' %}

{% load go_back_link %}

{% block title %}List of configurable options{% endblock %}

{% block header %}List of configurable options{% endblock %}

{% block content %}
    <div class="config_options_wrapper">
      {% if options %}
      {% for opt in options %}
          {% if display_only_editable_options or opt.can_override or can_edit_global_config %}
          <div class="option">
            <dt class="key">{{opt.key}}
              <div class="actions">
                {%if opt.can_override%}<a href="{{opt.key}}/" class="local"><span>edit</span></a> {%endif%}
                {%if can_edit_global_config%}<a href="{{opt.key}},global/" class="global"><span>edit global</span></a> {%endif%}
              </div>
            </dt>
            {% if opt.can_override %}
                <dd class="value"><span class="label">Value</span>: {{opt.value}}</dd>
            {%endif%}
            {% if can_edit_global_config %}
                <dd class="global_value"><span class="label">Global value</span>: {{opt.global_value}}</dd>
            {% endif %}
            <dd class="desc">{{opt.description}}</dd>
          </div>
          {% endif %}
      {% endfor %}
      {% else %}
      <p>No config options were found.</p>
      {% endif %}
    </div>

    {% go_back_link %}

{% endblock %}